### PR TITLE
divergent colors to landing map

### PR DESCRIPTION
**Pull request by hjohns12**
new colors -- i'm a little concerned about red/blue partisan associations.

### CODE REVIEW

**Comment by jamesturk** [comment]
adding screenshot
Screen Shot 2019-07-16 at 12 46 31 PM

**Comment by jamesturk** [comment]
I do think it looks partisan, especially since at a glance the south is more red, etc.

I wonder if diverging is correct since it is actually (sort of) a progression? (I could see either way though)

Maybe we're better off avoiding red/blue altogether and sticking with something using purple/green/orange/etc

**Comment by hjohns12** [comment]
Screen Shot 2019-07-16 at 2 10 52 PM
Here's a yellow-brown sequential color scheme.

**Comment by hjohns12** [comment]
It's a bit tricky to get a sequential palette where the lightest color is dark enough to show the "independent commissions" states AND the colors are differentiable from each other. Think divergent colors make it easier to differentiate the states, but then the progression isn't obvious

**Pull request merged**
